### ISSUE TITLE
Problems with 1.18.2

### ISSUE THREAD

**Issue by Toseflo** [ItsAZZA/LightBlockZ#4]
**Server information**
```
Server version:  paper-1.18.2-268.jar
Plugin version: 1.2.3
```

**Describe the bug**
The plugin was working fine in 1.18.1. Since 1.18.2, /lighttool doesn't work anymore and right clicking a light block in your inventory doesn't open the GUI to change the light value. I attached a file with the server log.
[latest.log](https://github.com/ItsAZZA/LightBlockZ/files/8365605/latest.log)

**Comment by ItsAZZA** [comment]
Thanks for the report! The plugin doesn't support 1.18.2 yet. Because of the NMS changes in 1.18.2 vs. 1.18.1, some changes need to be done. I'll get to these as soon as possible.

**Comment by ItsAZZA** [comment]
Fixed in the latest release!
